services:
  web:
    build: .
    volumes:
      - .:/app
      - /home:/home:ro
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5432/zerodayf
    ports:
      - "127.0.0.1:1337:1337"
    restart: always
