services:
  web:
    build: .
    network_mode: "host"
    volumes:
      - .:/app
      - /home:/home:ro
    environment:
      - DATABASE_URL=postgresql+asyncpg://test:test@localhost:5757/zerodayf
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=zerodayf
    ports:
      - "5757:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d zerodayf"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: